POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "aasim@test1.com",
    "password": "password",
    "confirmPassword": "password",
    "role": 2
}

### Login

POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email": "aasim1@zipfeast.com",
    "password": "aasim"
}